### PR TITLE
Forgot Password title isn't translated

### PR DESCRIPTION
**Pull request by peterjaap**

### CODE REVIEW

**Comment by peterjaap** [comment]
Will do it through Crowdin

**Comment by peterjaap** [comment]
Can't seem to add strings to Crowdin, only translate existing ones.

**Comment by MrGekko** [comment]
Thats is a issue that the Magento team can figure out.. I do not manage the crowdin repo...
But a repo like https://github.com/mageplaza/magento-2-dutch-language-pack has a option to combine with a csv file in the repo. I dont have the time unfortunately to add such a feature...

**Comment by arnoudhgz** [comment]
@peterjaap  it is actually a bug in Magento, the string should be "Password forgotten", I made a PR for Magento for this: https://github.com/magento/magento2/pull/18598

**Pull request closed without merging**
